name: "Add Reviewers to PR"
on:
  pull_request:
    types:
      - opened
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Add reviewers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add reviewers step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: umutzenger-popcore/pr-add-reviewer-action@v1.0 # Uses an action in the root directory
        with:
          reviewers: "aleksandr-popcore"